dev:
  datasource:
    mysql:
      ip: 192.168.11.100
      prot: 3366
      username: root
      password: 123
    redis:
      ip: 47.93.21.238
      port: 6379
      username: root
      password: 123
  zookeeper:
    ip: 192.168.11.100
    port: 2181
test:
  datasource:
    mysql:
      ip: 39.98.39.112
      prot: 3366
      username: root
      password: 123
    redis:
      ip: 47.93.21.238
      port: 6379
      username: root
      password: 123
  zookeeper:
    ip: 39.98.39.112
    port: 2181
